import { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { 
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { 
  CheckCircle2, Circle, Clock, Plus, Sparkles, 
  Loader2, Pencil, AlertTriangle, Target, ArrowUpDown,
  Eye
} from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useMultiTenant } from '@/hooks/useMultiTenant';
import { toast } from 'sonner';
import { questionnaire } from '@/data/questionnaire';
import { 
  generateActionsFromAssessment, 
  formatActionsForDatabaseInsert 
} from '@/lib/signalEngine';
import { getHumanRationale, cleanActionTitle, cleanActionDescription, priorityDisplay, statusDisplay, resetPatternUsage } from '@/lib/actionRationaleMap';
import { ActionSheet } from './ActionSheet';

interface Action {
  id: string;
  department: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  action_title: string;
  action_description: string;
  status: 'Open' | 'In Progress' | 'Completed';
  responsible_person: string | null;
  target_completion_date: string | null;
  support_required_from: string[];
  kpis_linked_to: string[];
  assessment_id: string | null;
  organization_id: string | null;
  user_id: string | null;
  updated_at?: string;
  _loadedAt?: string;
}

export function ActionPlan({ assessmentId }: { assessmentId?: string }) {
  const { user } = useAuth();
  const { currentOrganization, canPerformAction } = useMultiTenant();
  const [actions, setActions] = useState<Action[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterPriority, setFilterPriority] = useState<string>('all');
  const [sortBy, setSortBy] = useState<'priority' | 'status' | 'date'>('priority');
  
  // Edit/create state
  const [editingAction, setEditingAction] = useState<Action | null>(null);
  const [sheetMode, setSheetMode] = useState<'create' | 'edit'>('edit');
  const [sheetOpen, setSheetOpen] = useState(false);
  const [conflictDetected, setConflictDetected] = useState(false);
  const [conflictAction, setConflictAction] = useState<Action | null>(null);
  
  // Regeneration confirmation
  const [showRegenerateConfirm, setShowRegenerateConfirm] = useState(false);

  // Permission check
  const canEdit = canPerformAction('update');
  const canCreate = canPerformAction('create');

  // Calculate progress stats
  const completedCount = actions.filter(a => a.status === 'Completed').length;
  const totalCount = actions.length;
  const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  const overdueCount = actions.filter(a => {
    if (!a.target_completion_date || a.status === 'Completed') return false;
    return new Date(a.target_completion_date) < new Date();
  }).length;

  useEffect(() => {
    loadActions();
  }, [user, assessmentId, currentOrganization]);

  // A2: Multi-tenant scoped action loading — strict single-user fallback if no org
  const loadActions = async () => {
    if (!user) return;
    
    setLoading(true);
    try {
      let query = supabase
        .from('improvement_actions')
        .select('*')
        .order('created_at', { ascending: false });

      // Scope by organization if available, else strict user-only
      if (currentOrganization?.id) {
        query = query.eq('organization_id', currentOrganization.id);
      } else {
        query = query.eq('user_id', user.id);
      }

      if (assessmentId) {
        query = query.eq('assessment_id', assessmentId);
      }

      const { data, error } = await query;
      if (error) throw error;
      
      const actionsWithTimestamp = (data || []).map(a => ({
        ...a,
        _loadedAt: new Date().toISOString()
      }));
      setActions(actionsWithTimestamp as unknown as Action[]);
    } catch (error) {
      console.error('Error loading actions:', error);
      toast.error('Failed to load action plans');
    } finally {
      setLoading(false);
    }
  };

  // B1: Auto-generated action detection — uses signal metadata in description
  const isAutoGenerated = (action: Action) => 
    action.assessment_id === assessmentId && action.action_description?.includes('Triggered because:');

  const hasAutoGeneratedActions = actions.some(isAutoGenerated);

  const handleGenerateClick = () => {
    if (hasAutoGeneratedActions) {
      setShowRegenerateConfirm(true);
    } else {
      generateIntelligentActions(false);
    }
  };

  const generateIntelligentActions = async (replaceExisting: boolean) => {
    if (!user) return;
    
    setGenerating(true);
    setShowRegenerateConfirm(false);
    
    try {
      let targetAssessmentId = assessmentId;
      
      if (!targetAssessmentId) {
        const { data: assessments } = await supabase
          .from('assessments')
          .select('id, answers')
          .eq('user_id', user.id)
          .order('created_at', { ascending: false })
          .limit(1)
          .single();

        if (!assessments) {
          toast.error('No assessment found. Please complete an assessment first.');
          setGenerating(false);
          return;
        }
        targetAssessmentId = assessments.id;
      }

      // B1: If replacing, delete ONLY auto-generated actions (preserve manual ones)
      if (replaceExisting && targetAssessmentId) {
        const existingAutoActions = actions.filter(a => 
          a.assessment_id === targetAssessmentId && 
          a.action_description?.includes('Triggered because:')
        );
        if (existingAutoActions.length > 0) {
          const { error: deleteError } = await supabase
            .from('improvement_actions')
            .delete()
            .in('id', existingAutoActions.map(a => a.id));
          if (deleteError) console.error('Error deleting old auto-actions:', deleteError);
        }
      }

      const { data: assessment } = await supabase
        .from('assessments')
        .select('answers')
        .eq('id', targetAssessmentId)
        .single();

      if (!assessment) {
        toast.error('Failed to load assessment data');
        setGenerating(false);
        return;
      }

      // Build question weights from questionnaire
      const questionWeights: Record<string, number> = {};
      for (const section of questionnaire.sections) {
        for (const question of section.questions) {
          questionWeights[question.id] = question.weight;
        }
      }

      // Use canonical signal engine for action generation
      const generatedActions = generateActionsFromAssessment(
        assessment.answers as Record<string, number>,
        questionWeights
      );

      if (generatedActions.length === 0) {
        toast.success('No critical improvement areas found.');
        setGenerating(false);
        return;
      }

      // Format for database insertion
      const actionsWithOrg = formatActionsForDatabaseInsert(
        generatedActions,
        user.id,
        targetAssessmentId!,
        currentOrganization?.id || ''
      );

      const { data: insertedActions, error: insertError } = await supabase
        .from('improvement_actions')
        .insert(actionsWithOrg as any)
        .select();

      if (insertError) throw insertError;

      toast.success(`Generated ${insertedActions?.length || 0} targeted action items`);
      loadActions();
    } catch (error) {
      console.error('Error generating actions:', error);
      toast.error('Failed to generate action plans');
    } finally {
      setGenerating(false);
    }
  };

  // Open edit or create dialog (A4: centered modal)
  const openEditPanel = (action: Action) => {
    if (!canEdit) {
      toast.info('You have view-only access to actions.');
      return;
    }
    setEditingAction(action);
    setSheetMode('edit');
    setSheetOpen(true);
  };

  const openCreatePanel = () => {
    setEditingAction(null);
    setSheetMode('create');
    setSheetOpen(true);
  };

  // Save with conflict detection
  const handleSheetSave = async (formData: Partial<Action>) => {
    if (!user) return;
    
    if (sheetMode === 'create') {
      try {
        const actionData = {
          user_id: user.id,
          assessment_id: assessmentId || null,
          organization_id: currentOrganization?.id || null,
          department: formData.department || 'General',
          priority: formData.priority || 'medium',
          action_title: formData.action_title || '',
          action_description: formData.action_description || '',
          status: formData.status || 'Open',
          responsible_person: formData.responsible_person || null,
          target_completion_date: formData.target_completion_date || null,
          support_required_from: formData.support_required_from || [],
          kpis_linked_to: formData.kpis_linked_to || []
        };

        const { error } = await supabase
          .from('improvement_actions')
          .insert([actionData as any]);

        if (error) throw error;
        toast.success('Action added successfully');
        loadActions();
      } catch (error) {
        console.error('Error adding action:', error);
        toast.error('Failed to add action');
      }
    } else if (sheetMode === 'edit' && formData.id) {
      // Edit existing action with conflict detection
      try {
        const original = actions.find(a => a.id === formData.id);
        
        if (original?.updated_at) {
          const { data: currentAction } = await supabase
            .from('improvement_actions')
            .select('*')
            .eq('id', formData.id)
            .single();

          if (currentAction) {
            const currentData = currentAction as unknown as { updated_at?: string };
            if (currentData?.updated_at) {
              const serverTime = new Date(currentData.updated_at).getTime();
              const loadedTime = new Date(original.updated_at).getTime();
              
              if (serverTime > loadedTime) {
                // A3: Conflict — timestamp only, no user attribution
                setConflictAction(currentAction as unknown as Action);
                setConflictDetected(true);
                return;
              }
            }
          }
        }

        await performUpdate(formData);
      } catch (error) {
        console.error('Error updating action:', error);
        toast.error('Failed to update action');
      }
    }
  };

  const performUpdate = async (formData: Partial<Action>) => {
    const { error } = await supabase
      .from('improvement_actions')
      .update({
        action_title: formData.action_title,
        action_description: formData.action_description,
        department: formData.department,
        priority: formData.priority,
        status: formData.status,
        responsible_person: formData.responsible_person || null,
        target_completion_date: formData.target_completion_date || null,
        support_required_from: formData.support_required_from || [],
        kpis_linked_to: formData.kpis_linked_to || [],
        updated_at: new Date().toISOString()
      })
      .eq('id', formData.id!);

    if (error) throw error;
    toast.success('Action updated successfully');
    setSheetOpen(false);
    setConflictDetected(false);
    loadActions();
  };

  const handleDelete = async (actionId: string) => {
    try {
      const { error } = await supabase
        .from('improvement_actions')
        .delete()
        .eq('id', actionId);
      if (error) throw error;
      toast.success('Action deleted');
      loadActions();
    } catch (error) {
      console.error('Error deleting action:', error);
      toast.error('Failed to delete action');
    }
  };

  const updateActionStatus = async (actionId: string, newStatus: Action['status']) => {
    if (!canEdit) {
      toast.info('You have view-only access.');
      return;
    }
    try {
      const { error } = await supabase
        .from('improvement_actions')
        .update({ status: newStatus, updated_at: new Date().toISOString() })
        .eq('id', actionId);

      if (error) throw error;
      setActions(actions.map(action => 
        action.id === actionId ? { ...action, status: newStatus } : action
      ));
      toast.success('Status updated');
    } catch (error) {
      console.error('Error updating status:', error);
      toast.error('Failed to update status');
    }
  };

  const getPriorityConfig = (priority: string) => {
    return priorityDisplay[priority as keyof typeof priorityDisplay] || priorityDisplay.medium;
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Completed': return <CheckCircle2 className="h-4 w-4 text-green-600" />;
      case 'In Progress': return <Clock className="h-4 w-4 text-blue-600" />;
      default: return <Circle className="h-4 w-4 text-muted-foreground" />;
    }
  };

  // Filter and sort actions
  const filteredActions = actions
    .filter(action => {
      if (filterStatus !== 'all' && action.status !== filterStatus) return false;
      if (filterPriority !== 'all' && action.priority !== filterPriority) return false;
      return true;
    })
    .sort((a, b) => {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      const statusOrder = { 'Open': 0, 'In Progress': 1, 'Completed': 2 };
      
      if (sortBy === 'priority') {
        return priorityOrder[a.priority] - priorityOrder[b.priority];
      }
      if (sortBy === 'status') {
        return statusOrder[a.status] - statusOrder[b.status];
      }
      if (sortBy === 'date' && a.target_completion_date && b.target_completion_date) {
        return new Date(a.target_completion_date).getTime() - new Date(b.target_completion_date).getTime();
      }
      return 0;
    });

  // B3: Reset pattern usage for this render cycle to ensure uniqueness
  resetPatternUsage();

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="text-center space-y-4">
            <Loader2 className="h-8 w-8 animate-spin mx-auto text-primary" />
            <p className="text-muted-foreground">Loading action plan...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* View-only banner for restricted roles */}
      {!canEdit && (
        <Card className="bg-muted/50 border-muted">
          <CardContent className="py-3">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Eye className="h-4 w-4" />
              <span>Showing actions created under your user account.</span>
            </div>
          </CardContent>
        </Card>
      )}

      {/* P3.3: Progress Summary Card */}
      {totalCount > 0 && (
        <Card className="bg-gradient-to-r from-primary/5 to-primary/10 border-primary/20">
          <CardContent className="py-4">
            <div className="flex items-center justify-between flex-wrap gap-3">
              <div className="flex items-center gap-4 flex-wrap">
                <div className="flex items-center gap-2">
                  <Target className="h-5 w-5 text-primary" />
                  <span className="font-medium">
                    {completedCount} of {totalCount} actions completed
                  </span>
                </div>
                {overdueCount > 0 && (
                  <Badge variant="destructive" className="flex items-center gap-1">
                    <AlertTriangle className="h-3 w-3" />
                    {overdueCount} overdue
                  </Badge>
                )}
              </div>
              <div className="w-48">
                <Progress value={progressPercent} className="h-2" />
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <CardTitle>Action Plan</CardTitle>
              <CardDescription>
                Strategic initiatives to improve dealership performance
              </CardDescription>
            </div>
            <div className="flex gap-2">
              {canEdit && (
                <Button
                  onClick={handleGenerateClick}
                  disabled={generating}
                  variant="default"
                >
                  {generating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 h-4 w-4" />
                      Generate Actions
                    </>
                  )}
                </Button>
              )}
              {canCreate && (
                <Button onClick={openCreatePanel} variant="outline">
                  <Plus className="mr-2 h-4 w-4" />
                  Add Action
                </Button>
              )}
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* B4: Clean filters — Status + Priority only */}
          <div className="flex flex-wrap gap-3 items-center">
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[140px]">
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="Open">Open</SelectItem>
                <SelectItem value="In Progress">In Progress</SelectItem>
                <SelectItem value="Completed">Completed</SelectItem>
              </SelectContent>
            </Select>

            <Select value={filterPriority} onValueChange={setFilterPriority}>
              <SelectTrigger className="w-[140px]">
                <SelectValue placeholder="Priority" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Priority</SelectItem>
                <SelectItem value="critical">Critical</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>

            <Button 
              variant="ghost" 
              size="sm"
              onClick={() => setSortBy(prev => prev === 'priority' ? 'status' : prev === 'status' ? 'date' : 'priority')}
              className="flex items-center gap-1 text-xs"
            >
              <ArrowUpDown className="h-3 w-3" />
              Sort: {sortBy === 'priority' ? 'Priority' : sortBy === 'status' ? 'Status' : 'Due Date'}
            </Button>
          </div>

          {/* P3.1A: Table View */}
          {filteredActions.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Target className="h-12 w-12 mx-auto mb-4 opacity-20" />
              <p className="font-medium">No actions found</p>
              <p className="text-sm mt-1">Generate actions from your assessment or add them manually.</p>
            </div>
          ) : (
            <div className="border rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-8"></TableHead>
                    <TableHead>Action</TableHead>
                    <TableHead className="hidden md:table-cell">Department</TableHead>
                    <TableHead>Priority</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="hidden lg:table-cell">Owner</TableHead>
                    <TableHead className="hidden lg:table-cell">Due Date</TableHead>
                    {canEdit && <TableHead className="w-10"></TableHead>}
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredActions.map((action) => {
                    const priorityConfig = getPriorityConfig(action.priority);
                    // A1: Get rationale from action object (uses signal code from description, not department)
                    const rationale = getHumanRationale({ 
                      action_description: action.action_description,
                      department: action.department,
                      action_title: action.action_title
                    });
                    // B2/B4: Clean title and description
                    const displayTitle = cleanActionTitle(action.action_title);
                    const displayDesc = cleanActionDescription(action.action_description);

                    return (
                      <TableRow 
                        key={action.id} 
                        className="cursor-pointer hover:bg-muted/50"
                        onClick={() => openEditPanel(action)}
                      >
                        <TableCell className="pr-0">
                          {getStatusIcon(action.status)}
                        </TableCell>
                        <TableCell>
                          <div className="space-y-1">
                            <p className="font-medium text-sm leading-tight">{displayTitle}</p>
                            <p className="text-xs text-muted-foreground line-clamp-1">{rationale.summary}</p>
                          </div>
                        </TableCell>
                        <TableCell className="hidden md:table-cell">
                          <Badge variant="secondary" className="text-xs">{action.department}</Badge>
                        </TableCell>
                        <TableCell>
                          <Badge className={`${priorityConfig.color} text-xs`}>
                            {priorityConfig.label}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {canEdit ? (
                            <Select
                              value={action.status}
                              onValueChange={(value) => {
                                updateActionStatus(action.id, value as Action['status']);
                              }}
                            >
                              <SelectTrigger 
                                className="w-[120px] h-7 text-xs"
                                onClick={(e) => e.stopPropagation()}
                              >
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="Open">Open</SelectItem>
                                <SelectItem value="In Progress">In Progress</SelectItem>
                                <SelectItem value="Completed">Completed</SelectItem>
                              </SelectContent>
                            </Select>
                          ) : (
                            <span className="text-xs text-muted-foreground">{action.status}</span>
                          )}
                        </TableCell>
                        <TableCell className="hidden lg:table-cell text-xs text-muted-foreground">
                          {action.responsible_person || '—'}
                        </TableCell>
                        <TableCell className="hidden lg:table-cell text-xs text-muted-foreground">
                          {action.target_completion_date 
                            ? new Date(action.target_completion_date).toLocaleDateString()
                            : '—'}
                        </TableCell>
                        {canEdit && (
                          <TableCell>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 w-7 p-0"
                              onClick={(e) => {
                                e.stopPropagation();
                                openEditPanel(action);
                              }}
                            >
                              <Pencil className="h-3 w-3" />
                            </Button>
                          </TableCell>
                        )}
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}

          {/* Assessment data source note */}
          <p className="text-xs text-muted-foreground text-right">Based on assessment data</p>
        </CardContent>
      </Card>

      {/* Edit/Create Dialog (A4: centered modal) */}
      <ActionSheet
        open={sheetOpen}
        onOpenChange={setSheetOpen}
        action={editingAction}
        mode={sheetMode}
        onSave={handleSheetSave}
        onDelete={canEdit ? handleDelete : undefined}
        readOnly={!canEdit}
        rationale={editingAction ? getHumanRationale({ 
          action_description: editingAction.action_description,
          department: editingAction.department,
          action_title: editingAction.action_title
        }) : undefined}
        cleanDescription={editingAction ? cleanActionDescription(editingAction.action_description) : undefined}
      />

      {/* A3: Conflict Resolution Dialog — timestamp only */}
      <AlertDialog open={conflictDetected} onOpenChange={setConflictDetected}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-yellow-500" />
              Edit Conflict Detected
            </AlertDialogTitle>
            <AlertDialogDescription>
              This action has been modified since you started editing. 
              Would you like to review the latest version or overwrite with your changes?
            </AlertDialogDescription>
          </AlertDialogHeader>
          
          {conflictAction && (
            <div className="p-4 bg-muted rounded-md text-sm">
              <p><strong>Latest version:</strong></p>
              <p className="mt-1">{cleanActionTitle(conflictAction.action_title)}</p>
              <p className="text-xs text-muted-foreground mt-2">
                Updated: {conflictAction.updated_at ? new Date(conflictAction.updated_at).toLocaleString() : 'Unknown'}
              </p>
            </div>
          )}

          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => {
              setConflictDetected(false);
              if (conflictAction) {
                setEditingAction(conflictAction);
              }
              loadActions();
            }}>
              Review Latest
            </AlertDialogCancel>
            <AlertDialogAction onClick={async () => {
              if (editingAction) {
                try {
                  await performUpdate(editingAction);
                } catch (error) {
                  toast.error('Failed to overwrite');
                }
              }
              setConflictDetected(false);
            }}>
              Overwrite
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* B1: Regeneration confirmation dialog */}
      <AlertDialog open={showRegenerateConfirm} onOpenChange={setShowRegenerateConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Regenerate Actions?</AlertDialogTitle>
            <AlertDialogDescription>
              Auto-generated actions already exist for this assessment. 
              Regenerating will replace them with new ones. Manually created actions will be preserved.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={() => generateIntelligentActions(true)}>
              Regenerate
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
