// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrypgosuyfdkkqafftae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyeXBnb3N1eWZka2txYWZmdGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDYzMTgsImV4cCI6MjA2OTIyMjMxOH0.b6unq8fliuiT7Y58kAQxaM5LaqC1DVWKO5cdEADX-i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
// hello bello